### ISSUE TITLE
Content needed

### ISSUE THREAD

**Issue by Bill-A** [Bill-A/larocha-health#4]
- [x] picture of Daisy Rodriguez
- [x] content for Blog posts
- Any of the following contact info:
- [ ] Phone
- [ ] Address
- [ ] Fax ?
- [ ] Facebook ?
- [ ] Twitter ?
- [ ] Skype ?
- [ ] Instagram ?

**Comment by lmcfinn** [comment]
![daisy_rodriguez](https://cloud.githubusercontent.com/assets/22804271/26663803/da1e4c2a-4652-11e7-9fbe-06b42a2d9a52.jpg)
![lassa](https://cloud.githubusercontent.com/assets/22804271/26663813/e57e9638-4652-11e7-9b31-e7ba387c98c9.jpg)

**Comment by Bill-A** [comment]
![daisy_rodriguez_w321](https://cloud.githubusercontent.com/assets/1857789/26689370/0c8b4042-46bb-11e7-840a-024c8b170ef9.jpg)
![jerry_lassa-2_w321](https://cloud.githubusercontent.com/assets/1857789/26689369/0c79fb2a-46bb-11e7-991d-839a0a76e0dd.jpg)

**Comment by Bill-A** [comment]
@lmcfinn I resized the images.

**Comment by Bill-A** [comment]
Blog entry options:

https://chicagodefender.com/2011/11/08/rhymefest-talks-about-life-with-diabetes/

http://www.besthealthmag.ca/best-you/diabetes/how-to-track-your-blood-sugar-levels/

**Comment by lmcfinn** [comment]
Phone: 773 - 428 - 2991
Address: 2714 N Lehmann Court #4, Chicago IL 60614
